blueprint:
  name: Challenge entity updater
  description: This will update a Challenge entity based on time and a HILO sensor
  domain: automation

  input:
    challenge_entity:
      name: Challenge selector entity
      description: Input text to change depending on time
      selector:
        entity:
          domain: input_text

    challenge_in_progress:
      name: Challenge in progress
      description: Entity stating if a challenge is in progress
      selector:
        entity:
          domain: sensor

    hilo_or_hydro:
      name: Hilo or Hydro-Québec
      description: Use challenges hours from Hilo or Hydro-Québec
      selector:
        select:
          options:
            - label: Hydro
              value: Hydro
            - label: Hilo
              value: Hilo

variables:
  hilo_or_hydro: !input hilo_or_hydro

trigger:
  - platform: time
    at: "01:01"

  - platform: time
    at: "04:00"

  - platform: time
    at: "05:00"

  - platform: time
    at: "06:00"

  - platform: time
    at: "09:00"

  - platform: time
    at: "10:00"

  - platform: time
    at: "12:01"

  - platform: time
    at: "15:00"

  - platform: time
    at: "16:00"

  - platform: time
    at: "17:00"

  - platform: time
    at: "20:00"

  - platform: time
    at: "21:00"

  - platform: state
    entity_id:
      - sensor.defi_hilo

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "00:59:00"
                before: "04:00:00"
              - condition: time
                after: "11:59:00"
                before: "15:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "False"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: ref_appreciation
                    target:
                      entity_id: input_text.hilo_challenge

              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "True"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: appreciation
                    target:
                      entity_id: input_text.hilo_challenge

      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ hilo_or_hydro == 'Hydro' }}"
                  - condition: or
                    conditions:
                      - condition: time
                        after: "06:00:00"
                        before: "09:00:00"
                      - condition: time
                        after: "17:00:00"
                        before: "20:00:00"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ hilo_or_hydro == 'Hilo' }}"
                  - condition: or
                    conditions:
                      - condition: time
                        after: "06:00:00"
                        before: "10:00:00"
                      - condition: time
                        after: "17:00:00"
                        before: "21:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "False"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: ref_challenge
                    target:
                      entity_id: input_text.hilo_challenge

              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "True"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: challenge
                    target:
                      entity_id: input_text.hilo_challenge

      - conditions:
          - condition: state
            entity_id: !input challenge_in_progress
            state: "True"
          - condition: or
            conditions:
              - condition: time
                after: "05:00:00"
                before: "06:00:00"
              - condition: time
                after: "16:00:00"
                before: "17:00:00"
        sequence:
          - service: input_text.set_value
            data:
              value: preheat
            target:
              entity_id: input_text.hilo_challenge

    default:
      - service: input_text.set_value
        data:
          value: normal
        target:
          entity_id: input_text.hilo_challenge