blueprint:
  name: Challenge entity updater
  description: This will update a Challenge entity based on time and a HILO sensor
  domain: automation

  input:
    challenge_entity:
      name: Challenge selector entity
      description: Input_text entity thas was manualy created
      selector:
        entity:
          domain: input_text

    challenge_in_progress:
      name: Challenge in progress
      description: Sensor created in the configuration file
      selector:
        entity:
          domain: sensor

trigger:
  - platform: time
    at: "01:01"

  - platform: time
    at: "04:00"

  - platform: time
    at: "05:00"

  - platform: time
    at: "06:00"

  - platform: time
    at: "10:00"

  - platform: time
    at: "12:01"

  - platform: time
    at: "15:00"

  - platform: time
    at: "16:00"

  - platform: time
    at: "17:00"

  - platform: time
    at: "21:00"

  - platform: state
    entity_id:
      - sensor.defi_hilo

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "00:59:00"
                before: "04:00:00"
              - condition: time
                after: "11:59:00"
                before: "15:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "False"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: ref_appreciation
                    target:
                      entity_id: !input challenge_entity

              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "True"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: appreciation
                    target:
                      entity_id: !input challenge_entity

      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "06:00:00"
                before: "10:00:00"
              - condition: time
                after: "17:00:00"
                before: "21:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "False"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: ref_challenge
                    target:
                      entity_id: !input challenge_entity
              - conditions:
                  - condition: state
                    entity_id: !input challenge_in_progress
                    state: "True"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: challenge
                    target:
                      entity_id: !input challenge_entity

      - conditions:
          - condition: state
            entity_id: !input challenge_in_progress
            state: "True"
          - condition: or
            conditions:
              - condition: time
                after: "05:00:00"
                before: "06:00:00"
              - condition: time
                after: "16:00:00"
                before: "17:00:00"
        sequence:
          - service: input_text.set_value
            data:
              value: preheat
            target:
              entity_id: !input challenge_entity

    default:
      - service: input_text.set_value
        data:
          value: normal
        target:
          entity_id: !input challenge_entity
