blueprint:
  name: Hilo - Entité de référence automatique
  description: Changement automatique de l'entité de référence pour les défis
  domain: automation

  input:
    challenge_entity:
      name: Entité de sélection
      description: Input_text créé manuellement
      selector:
        entity:
          domain: input_text

    default_challenge_entity:
      name: Entité de défi par défaut de l'intégration (pour la phase de refroidissement)
      selector:
        entity:
          domain: sensor

    do_pre_heat:
      name: Activer le pré-chauffage
      description: Pré-chauffer avant la réduction (équivalent au pré-chauffage de l'appli Hilo)
      default: true
      selector:
        boolean:

trigger:
  - platform: time_pattern
    minutes: /1

variables:
  do_pre_heat: !input do_pre_heat

action:
  - choose:
      # Verification de la periode d'appreciation (doit etre configurer pour un max de 3h dans l'intégration de Hilo)
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "01:00:00"
                before: "04:00:00"
              - condition: time
                after: "12:00:00"
                before: "15:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input default_challenge_entity
                    state: "appreciation"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: "appreciation"
                    target:
                      entity_id: !input challenge_entity
            default:
              - service: input_text.set_value
                data:
                  value: "ref_appreciation"
                target:
                  entity_id: !input challenge_entity
                      
      # Verification pour la periode de refroidissement avant l'appreciation (doit etre configuré pour un max de 1h dans l'intégration de Hilo)
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "00:00:00"
                before: "01:00:00"
              - condition: time
                after: "11:00:00"
                before: "12:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input default_challenge_entity
                    state: "pre_cold"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: "pre_cold"
                    target:
                      entity_id: !input challenge_entity
            default:
              - service: input_text.set_value
                data:
                  value: "normal"
                target:
                  entity_id: !input challenge_entity

      # Verification de defis en cours (reduction ou on)
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "06:00:00"
                before: "10:00:00"
              - condition: time
                after: "17:00:00"
                before: "21:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: !input default_challenge_entity
                        state: "reduction"
                      - condition: state
                        entity_id: !input default_challenge_entity
                        state: "on"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: "reduction"
                    target:
                      entity_id: !input challenge_entity
            default:
              - service: input_text.set_value
                data:
                  value: "ref_reduction"
                target:
                  entity_id: !input challenge_entity

      # Verification de Pre_heat avant la reduction SI do_pre_heat est activé
      - conditions:
          - condition: or
            conditions:
              - condition: time
                after: "04:00:00"
                before: "06:00:00"
              - condition: time
                after: "15:00:00"
                before: "17:00:00"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input default_challenge_entity
                    state: "pre_heat"
                  - condition: template
                    value_template: "{{ do_pre_heat | bool }}"
                sequence:
                  - service: input_text.set_value
                    data:
                      value: "pre_heat"
                    target:
                      entity_id: !input challenge_entity
            default:
              - service: input_text.set_value
                data:
                  value: "normal"
                target:
                  entity_id: !input challenge_entity
            

    default:
      - service: input_text.set_value
        data:
          value: "normal"
        target:
          entity_id: !input challenge_entity
