blueprint:
  name: Défis Hilo automatiques
  description: Optimise les températures basées sur les défis Hilo
  domain: automation

  input:
    challenge_entity:
      name: Entité de phase de défi
      description: Input_text entity thas was manualy created
      selector:
        entity:
          domain: input_text

    challenge_am:
      name: Défi AM
      description: Va participer aux défis AM (incluant la référence)
      default: true
      selector:
        boolean:

    challenge_pm:
      name: Défi PM
      description: Va participer aux défis PM (incluant la référence)
      default: true
      selector:
        boolean:

    thermostats:
      name: Thermostats
      selector:
        entity:
          domain: climate
          multiple: true

    water_heater:
      name: Chauffe-eau (optionnel)
      description: Désactive le chauffe-eau durant les défis et les phases d'appréciation de référence
      default: null
      selector:
        entity:
          domain: switch

    other_devices:
      name: Autres équipements (optionnel)
      description: Désactive d'autres équipements durant les défis et/ou les phases d'appréciation de référence
      default: null
      selector:
        entity:
          domain: switch
          multiple: true

    bool_ref_water_heater:
      name: Défis seulement ou Refroidissment et Défis 
      description: Désactive le chauffe eaux durant les défis seulement (False) ou désactiver durant la phase de refroidissement, puis réactivation durant la phase d'appréciation avec de désactiver pour les défis (True)
      default: False
      selector:
        boolean:
        
    bool_ref_other:
      name: Défis seulement ou Refroidissment/Appréciations/Défis 
      description: Désactive les autres équipements durant les défis seulement (False) ou désactiver durant la phase de refroidissement, puis réactivation durant la phase d'appréciation avec de désactiver pour les défis (True)
      default: False
      selector:
        boolean:

    normal_temp:
      name: Température normale
      description: Température pour les moments sans défis (ni référence, ni appréciation)
      default: 21
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    reference_temp:
      name: Température de référence
      description: Température pour les phases de références (plus haute que la normale) (faible impact sur les récompenses)
      default: 22
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    cooling_temp:
      name: Température de refroidissement
      description: Température pour les phases de refroidissement avant appréciation (si activé)
      default: 20
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    appreciation_reference_temp:
      name: Température de la référence d'appréciation
      description: Température pour les phases d'appréciation de référence (plus basse que normale) (impact modéré sur les récompenses)
      default: 20
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    appreciation_temp:
      name: Température de l'appréciation
      description: Température pour les phases d'appréciation (plus haute que normale) (impact important sur les récompenses)
      default: 23
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    preheat_temp:
      name: Température de pré-chauffage
      description: Température durant la phase de pré-chauffage (aucun impact sur les récompenses)
      default: 23
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    challenge_temp:
      name: Température de défi
      description: Température lors des défis (le plus bas possible)
      default: 17
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

trigger:
  - platform: state
    entity_id: !input challenge_entity

variables:
  water_heater: !input water_heater
  other_devices: !input other_devices
  challenge_am: !input challenge_am
  challenge_pm: !input challenge_pm

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ challenge_pm}}"
                  - condition: time
                    after: "11:55:00"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ challenge_am }}"
                  - condition: time
                    before: "11:55:00"
        sequence:
          - choose:
              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: ref_appreciation
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input appreciation_reference_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: "{{ other_devices|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input other_devices

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: appreciation
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input appreciation_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: "{{ other_devices|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input other_devices

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: pre_cold
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input cooling_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: 
                        - "{{ water_heater|length > 0 }}"
                        - "{{ bool_ref_water_heater == True }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: 
                        - "{{ other_devices|length > 0 }}"
                        - "{{ bool_ref_other == True }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input other_devices

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: ref_challenge
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input reference_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: "{{ other_devices|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input other_devices

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: challenge
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input challenge_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: "{{ other_devices|length > 0 }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input other_devices

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: preheat
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input preheat_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: "{{ other_devices|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input other_devices

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: normal
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input normal_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater
                  - choose:
                      - conditions: "{{ other_devices|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input other_devices
                              
    default:
      - service: climate.set_temperature
        data:
          temperature: !input normal_temp
        target:
          entity_id: !input thermostats
      - choose:
          - conditions: "{{ water_heater|length > 0 }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input water_heater
      - choose:
          - conditions: "{{ other_devices|length > 0 }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input other_devices
          
