blueprint:
  name: Generic Hydro-Québec Challenges
  description: Optimise temperatures based on the dynamic tarification with challenges
  domain: automation

  input:
    challenge_entity:
      name: Challenge selector entity
      description: Input_text entity thas was manualy created
      selector:
        entity:
          domain: input_text

    challenge_am:
      name: Challenge AM
      description: Will participate in the challenges in AM (reference included)
      default: true
      selector:
        boolean:

    challenge_pm:
      name: Challenge PM
      description: Will participate in the challenges in PM (reference included)
      default: true
      selector:
        boolean:

    thermostats:
      name: Thermostats
      selector:
        entity:
          domain: climate
          multiple: true

    water_heater:
      name: Water heater (optionnal)
      description: Disables the water heater during challenges and appreciation references
      default: null
      selector:
        entity:
          domain: switch

    normal_temp:
      name: Normal temperature
      description: Normal temperature for when no challenges are in place
      default: 21
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    reference_temp:
      name: Reference temperature
      description: Temperature to set during reference periods (higher than normal)
      default: 22
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    appreciation_reference_temp:
      name: Appreciation reference temperature
      description: Temperature to set during appreciation reference periods (lower than normal)
      default: 20
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    appreciation_temp:
      name: Appreciation temperature
      description: Temperature to set during appreciation phase (higher than normal)
      default: 23
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    preheat_temp:
      name: Pre heat temperature
      description: Temperature to increase during preheat periods (highest of all temperatures)
      default: 23
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

    challenge_temp:
      name: Challenge temperature
      description: Temperature to drop to during challenges (lowest of all temperatures)
      default: 17
      selector:
        number:
          step: 0.5
          min: 15
          max: 25
          unit_of_measurement: °C

trigger:
  - platform: state
    entity_id: !input challenge_entity

variables:
  water_heater: !input water_heater
  challenge_am: !input challenge_am
  challenge_pm: !input challenge_pm

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ challenge_pm}}"
                  - condition: time
                    after: "11:55:00"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ challenge_am }}"
                  - condition: time
                    before: "11:55:00"
        sequence:
          - choose:
              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: ref_appreciation
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input appreciation_reference_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: appreciation
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input appreciation_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: ref_challenge
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input reference_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: challenge
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input challenge_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input water_heater

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: preheat
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input preheat_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater

              - conditions:
                  condition: state
                  entity_id: !input challenge_entity
                  state: normal
                sequence:
                  - service: climate.set_temperature
                    data:
                      temperature: !input normal_temp
                    target:
                      entity_id: !input thermostats
                  - choose:
                      - conditions: "{{ water_heater|length > 0 }}"
                        sequence:
                          - service: switch.turn_on
                            target:
                              entity_id: !input water_heater
    default:
      - service: climate.set_temperature
        data:
          temperature: !input normal_temp
        target:
          entity_id: !input thermostats
      - choose:
          - conditions: "{{ water_heater|length > 0 }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: !input water_heater
